### ISSUE TITLE
Links to Glossary terms do not work in PDF Export

### ISSUE THREAD

**Issue by eufjan** [realtimeprojects/mkdocs-ezglossary#10]
Thanks a lot to this team for developing this plugin, it is a great ressource.

We have encountered a problem in PDF-Export: unfortunately the links to the terms in the Glossary do not work in the PDF Generated via [mkdocs-with-pdf](https://pypi.org/project/mkdocs-with-pdf/) . References to glossary terms are only formatted as links in the pdf but are not "active" links. Ordinary links to other sections work fine in the PDF.

Is there any solution how this can be resolved?

Setup is:
```
plugins:
  - search
  - table-reader
  - include_dir_to_nav
  - ezglossary:
       tooltip: full
  - kroki:
      ServerURL: https://kroki.hzdr.de
      FencePrefix: ''
      HttpMethod: GET
  - with-pdf
```
