### ISSUE TITLE
Unable to use unicode symbols in glossary

### ISSUE THREAD

**Issue by nfelt14** [realtimeprojects/mkdocs-ezglossary#12]
I have a glossary like this:

```
🚧
: Work in Progress

✅
: Implemented

❌
: Not Supported

IDE
: Integrated Development Environment
```

The symbols are not getting picked up and links are not getting created in the deflist.

This is the resulting html:
```html
<dl>
<dt>🚧</dt>
<dd>Work in Progress</dd>
<dt>✅</dt>
<dd>Implemented</dd>
<dt>❌</dt>
<dd>Not Supported</dd>
<dt>
	<a id="__IDE_defs_0">IDE</a> 
</dt>
<dd>Integrated Development Environment</dd>
</dl>
```

These are my plugin settings:
```
  - ezglossary:
      tooltip: full
      strict: true
      use_default: true
      inline_refs: none
      markdown_links: true
```

Is there something else I need to do in order to get the glossary to recognize those symbols?
