### ISSUE TITLE
Plural usages of singular terms are not listed in glossary

### ISSUE THREAD

**Issue by pekkaklarck** [realtimeprojects/mkdocs-ezglossary#24]
Now that #22 is fixed, plural usages of singular terms work, but these usages are not added as references to the glossary.

My configuration:

```yml
  - ezglossary:
      use_default: true
      ignore_case: true
      plurals: en
      tooltip: full
      inline_refs: list
```

Glossary entry:
```
Test
:  Definition
```

When I refer to the term like `<test:>`, the usage gets added to the glossary, but when I use it like `<tests:>` there's nothing. Link from the term to the glossary works in both cases.
