### ISSUE TITLE
Is it possible to have glossary links in the definition of a term?

### ISSUE THREAD

**Issue by segfaultxavi** [realtimeprojects/mkdocs-ezglossary#26]
This case does not seem to work for me:

```markdown
TermA
:   The opposite of <TermB:>.

TermB
:   The opposite of <TermA:>.
```

With this `mkdocs.yml`:
```yml
  ezglossary:
    use_default: true
    inline_refs: none
    tooltip: full
    ignore_case: true
```

The tooltips render as `The opposite of`, with the link stripped. 
I understand link titles cannot have links, but I believe they would be more useful if the link _text_ at least was preserved.
