### ISSUE TITLE
Cyrillic glossary entires are not recognized

### ISSUE THREAD

**Issue by syberside** [realtimeprojects/mkdocs-ezglossary#7]
Hi! 

Thank you for great plugin. It's great, but I faced an issue while trying to build glossary for my project.

When I put cyrillic entry to glossary it does not recognized properly. Looks like only english entries are supported.

Sample:
Glossary file
```
МП
: мобильное приложение
```

Ref in other document `<МП:>`

Result: no highlighting of term.

Settings
```
  - ezglossary:
      use_default: true
      tooltip: full
      inline_refs: short
```
